#Блок ввода исходных параметров для пласта (Жигулёвская нефть, Девонский горизонт)

#Количество шагов разбиения
N1 = 1000
#Мощность пласта, м
h = [8, 10, 9]
#Проницаемость пласта, м**2
k = [1.2e-12, 1.2e-12, 1.2e-12]
#Забойное давление (в начале скважины), Па
Pc = [13.3e+6, 18.6e+6, 24e+6]
#Давление на контуре питания, Па
Pk = [15e+6, 20e+6, 25.5e+6]
#Динамическая вязкость воды, Па*с
muN0 = 8.9e-4
#Радиус скважины, м
rc = [0.146, 0.168, 0.177]
#Радиус контура питания, м
rk = [700, 900, 1100]
#Коэффициент обводненности
alphav = 1


#Блок ввода параметров для скважины

#Количество шагов разбиения
N2 = 1000
#Относительная шероховатость
OTsheroh = 0.5e-3
#Толщина стенки скважины, м
thick = 0.01
#Температурный коэффициент объёмного расширения нефти 1/К
betaN = 4.73e-4
#Температурный коэффициент объёмного расширения воды 1/К
betaV = 1.1e-4
#Удельная теплоемкость нефти Дж/(кг*К)
CN = 1680
#Удельная теплоемкость воды Дж/(кг*К)
CV = 4200
#Удельная теплоёмкость материала стенки трубы Дж/(кг*К)
CSt = 462
#Глубины скважин, м
Hskv = [1000, 1500, 2000]
#Температурный градиент К/м
gradT = 0.03
#Температура грунта на глубине (зависит от глубины пролегания трубопровода H), К
Tgr = 283
#Коэффициент теплопроводности грунта Вт/м * К
lyambdaGr = 0.6
#Коэффициент теплопроводности воды Вт/м * К
lyambdaV = 0.669
#Коэффициент теплопроводности нефти Вт/м * К
lyambdaN0 = 0.134
#Коэффициент теплопроводности материала стенки трубы Вт/м * К (НКТ 30ХМА) 
lyambdaSt = 46
#Плотность нефти при нормальных условиях кг/м**3
po = 852.1
#Коэффициент технического состояний труб
E = 0.9
#Коэффициент местных сопротивлений TODO стр. 168 доработать
dzeta = 0

#Блок ввода параметров для трубопроводов: 1, 2, 3

#Количество шагов разбиения
N3 = 1000
#Диаметр трубопровода, внешний м
Dt = 0.25
#Длина трубопровода до узла соединения трубопроводов от скважин, м
L = [5000, 6000, 6400]
#Глубина пролегания трубопроводов, м
H = 1
#Толщина стенки трубопровода, м
thickT = 0.02

#Блок ввода параметров системы общего трубопровода.

#Количество шагов разбиения
N4 = 1000
#Длина общего трубопровода до узла сбора нефти, м
LTrO = 8000

#Константы

#Ускорение свободного падения
g = 9.81
#Критические числа Рейнольдса
Re1 = 2300
Re2 = 10000
#Число пи
pi = 3.1416
#Плотность воды
pov = 1000